(add-to-list 'load-path "~/.emacs.d/config")
(require 'init-theme)
(require 'init-font)
(require 'init-indent-line)
(require 'init-auto-complete)
(require 'init-js2-mode)
(require 'init-keyboard-bind)
(require 'init-other)
(require 'init-tabbar)
(require 'init-php-mode)
(require 'init-autopair)
(require 'init-evil)
;(require 'init-c++-mode)
